const os = require('os')

// console.log(os.hostname())
// console.log(os.cpus())
// console.log(os.availableParallelism())
// console.log(os.arch())
// console.log(os.freemem())
// console.log(os.totalmem())
// console.log(os.getPriority())
// console.log(os.homedir())
// console.log(os.loadavg())
// console.log(os.machine())
// console.log(os.networkInterfaces())
// console.log(os.version())
// console.log(os.userInfo())
